# -----------------------------------------------------------------------------
#
#
# -----------------------------------------------------------------------------

makefile_build:
	rm -rf build && mkdir build && cd build && cmake .. && cd ..

sublime_build:
	rm -rf build && mkdir build && cd build && cmake .. -G "Sublime Text 2 - Unix Makefiles" && cd ..

clean:
	rm -rf build CMakeLists.txt.user
